version: "3.7"

services:
  
  master:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: master
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./data/master:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - ./hadoop.env
    networks: 
      - hadoop_network

  worker1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: worker1
    restart: always
    volumes:
      - ./data/worker1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "master:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  
  worker2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: worker2
    restart: always
    volumes:
      - ./data/worker2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "master:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  worker3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: worker3
    restart: always
    volumes:
      - ./data/worker3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "master:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  
  yarn:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn
    restart: always
    environment:
      SERVICE_PRECONDITION: "master:9000 master:9870 worker1:9864 worker2:9864 worker3:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "master:9000 master:9870 worker1:9864 worker2:9864 yarn:8088 worker3:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "master:9000 master:9870 worker1:9864 worker2:9864 yarn:8088 worker3:9864"
    volumes:
      - ./data/hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network


networks:
  hadoop_network:
    external: true
  